sudo: required
dist: trusty
language: node_js
git:
  depth: 3
branches:
  only:
  - master
cache:
  directories:
  - node_modules
node_js:
- '6.4'
addons: 
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
install:
 - npm install
before_script:
- npm run compile:aot
- ls
script: npm run ci
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: susnutrition
  region: eu-west-1
  skip_cleanup: true
  local-dir: dist/client
  acl: public_read
  detect_encoding: true
  on:
    branch: master

## Setup notifications
notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: "CsIzLgGOz8ApiPy5xq9/MZuW1O1nYvRYgajtctp+/zVIr8Ty67zf/V+y3+c5um4E8o6avvcgOu+jseLC24rRE5WoZM6qeTCChChSDdLTiMXoe0G3eGV0MCbjegq6CQca1tlF+j2nzC8LedoFRN4VrS/AHLRXaoTTD
y2b+HnP7EmQsSiOnnJXuQs3bnR3OfgMsuh/G0LIrCz/UG1PIzkznJqeR+4jnTqSnMRLK/4fQRnfZpAIOg3MHE3ut1jCIx2Rtv1ouZXluRJS3X5Vg2+jugzgSMWvTHPXEjDWhqF7DRCs7Ku6UJhJxfOYuvNzOjnnWe9E1HSBE6/39
gEcrO9Exfb/GxyQo6GmMpjDpyj7SqTHcRjz3wNnfZjth9J1lyiJ7pQO0nwd3d9lNcZ8hI6W33813UJSQzP45hcA/w4QCuUDnI4XOm6noL8OMoG2bVWlHtdnrvRr9Lo17BeWzRQTdCZAH/6pqHn6v4YxT+ng4SnwinUspHpOrJP5J
gAtTjm7Zrhax9JCK64O3rIKnErMX6FicmGwWduCfF/Xc9QHfur5BPj6jQPcey/jgbj1WQw0w58y2G4fk1GVg57OcXhT2YUkvxD9thvKrAElu3axqcSkz19+u0yeGX56OYbZMP/RMngpQkYezQPsXAteZq3FWF8cWEC9ctBc/rF1p
xQ/hF8="
